server {
    listen 80;
    server_name futquinta.moteirodev.shop;

    # Mantém a rota para renovação do Certbot
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redireciona 🚦 qualquer outro acesso para o HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name futquinta.moteirodev.shop;

    # Aponta para os certificados gerados 🔐
    ssl_certificate /etc/letsencrypt/live/futquinta.moteirodev.shop/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/futquinta.moteirodev.shop/privkey.pem;

    # Entrega os arquivos do seu frontend 📄
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}